baseURL = "https://tpaidakis.com/"
locale = "en-us"
title = "tpaidakis"
paginate = 10
enableRobotsTXT = true

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[params]
  author = "Theo Paidakis"
  description = "grep -r \"password\" . enthusiast."
  since = "2024"
  twitterSite = ""

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Writeups"
    url = "/writeups/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
